version: "3"
services:
  MounteBank:
    container_name: MounteBank
    image: jkris/mountebank:latest
    volumes:
      - ./MountBankBankServiceImposters.json:/MountBankBankServiceImposters.json
    ports:
      - 2525:2525
      - 4545:4545
    command: --configfile /MountBankBankServiceImposters.json --allowInjection
  
  MYSQL:
    container_name: MYSQL
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306