version: "3"
services:
  mounte-bank:
    container_name: mounte-bank
    image: jkris/mountebank:latest
    restart: unless-stopped
    volumes:
      - ./MountBankBankServiceImposters.json:/MountBankBankServiceImposters.json
    ports:
      - 2525:2525
      - 6060:6060
      - 4545:4545
    command: --configfile /MountBankBankServiceImposters.json --allowInjection
  
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  
  payment-gateway:
    container_name: payment-gateway
    image: paymen-gateway
    restart: unless-stopped
    depends_on:
      - mysql
      - mounte-bank
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      BANK_SERVICE_URL: "http://mounte-bank:6060/payments"
      MYSQL_CONNECTION_STRING: "server=mysql;uid=root;pwd=admin;database=PaymentGateway"
    command: dotnet PaymentGateway.API.dll
    ports:
      - 80:80