version: "3"
services:
  MounteBank:
    container_name: MounteBank
    image: jkris/mountebank:latest
    volumes:
      - ./MountBankBankServiceImposters.json:/MountBankBankServiceImposters.json
    ports:
      - 2525:2525
      - 4545:4545
    command: --configfile /MountBankBankServiceImposters.json --allowInjection

  PaymentGatewayTest:
    container_name: PaymentGatewayTest
    image: mcr.microsoft.com/dotnet/sdk:3.1
    depends_on:
      - MounteBank
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BANK_SERVICE_URL=http://mountebank:4545/payments
      - MYSQL_CONNECTION_STRING="server=MYSQL;uid=root;pwd=admin;database=PaymentGateway"
    command: "dotnet run --project app/PaymentGateway.API/PaymentGateway.API.csproj"
  
  MYSQL:
    container_name: MYSQL
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306